### ISSUE TITLE
How to end redis when there is no more data in queue or all commands are sent and return?

### ISSUE THREAD

**Issue by yyfrankyy** [mranney/node_redis#332]
I wrote this function for shutdown redis when all jobs are done, is there any other easy way to do this?

```JavaScript
function shutdownSoon(redis, delay) {
  var callee = arguments.callee
  process.nextTick(function() {
    if (redis.offline_queue.length === 0) {
      redis.end()
    } else {
      setTimeout(function() {
        callee(redis)
      }, delay || 500)
    }
  })
}
```

**Comment by BridgeAR** [comment]
@yyfrankyy you want to end with `.quit` instead of `.end`. Quit ends the connection after all former jobs are done. This is actually the recommended way of doing it, since a while now.
