### ISSUE TITLE
When you suppose to scan command?

### ISSUE THREAD

**Issue by ahkimkoo** [mranney/node_redis#579]
SCAN isn't support, when you suppose to add it?

**Comment by MarkHerhold** [comment]
One year later, what is the current state of SCAN? @brycebaril , is your [redis-scanstreams](https://www.npmjs.org/package/redis-scanstreams) project still active?

**Comment by brycebaril** [comment]
@MarkHerhold the client has `client.scan` but I find https://www.npmjs.org/package/redis-scanstreams an easier abstraction for the SCAN command. Supported in both places.

**Comment by MarkHerhold** [comment]
@brycebaril Thanks for the response! Would you be open to a pull request to update dependencies? I'll move the conversation to your repo if needed.

**Comment by brycebaril** [comment]
Absolutely!
