### ISSUE TITLE
Strange ERR value is not a valid float message

### ISSUE THREAD

**Issue by twappworld** [mranney/node_redis#700]
Using NodeJS and Redis (promisified via BlueBird).

Getting inconsistent error:

Possibly unhandled Error: ERR value is not a valid float
    at ReplyParser.RedisClient.init_parser (/home/adam/Deep-Ads/node_modules/redis/index.js:317:31)

Any ideas?

**Comment by mranney** [comment]
Do you have any way to reproduce this?

If you can afford it in production, a useful thing to do is run with debug_mode set. This will log all of the raw protocol data in and out of the client. If we knew what data was being read right before this error, it'd be pretty straightforward to fix.

**Comment by drwicked** [comment]
I'm having this issue too. What did you find you?

**Comment by ganeshnaidu** [comment]
Check zadd statements. KEY,SCORE,VALUE.
You must have swapped score and value

**Comment by BridgeAR** [comment]
@twappworld did the comment from @ganeshnaidu help you?

**Comment by mitchellporter** [comment]
Just in case anyone find this issue and was having the same problem I was...

I was combining multiple values to get my score before setting it and one of my numbers was `NaN` which was causing this error. After fixing the 

- [ ] NaN

 the problem went away.

**Comment by douglaskruger** [comment]
Using the 'c' hiredis infrastructure, I get an error - but using the redis-cli with the same string - it returns fine.

redis-cli:
127.0.0.1:6379> ZADD modbus-alarm:0 0 1548650706:"Low Voltage Alarm at 7.11"
(integer) 1

However, the following string issued to the redisCommand function seems to error out and not insert the data... I have tried both single quotes and escaped double quotes when I built the string for the redisCommand.

ZADD modbus-alarm:0 0 1548650706:"Low Voltage Alarm at 7.11"
Redis Message:ERR value is not a valid float Type:6

Thoughts?

**Comment by pratikjoshibyjus** [comment]
> Check zadd statements. KEY,SCORE,VALUE.
> You must have swapped score and value

@fa1d87bc7f85769ea9dee2e4957321ae  what is wrong in `zadd queues:checkin:reserved process_id 1` Still I get the issue.

**Comment by varundhand** [comment]
I was trying to store a UUID as the score in a Redis zAdd operation, but I found out that the score field only accepts a **floating-point number**, not a string. If anyone else runs into this, make sure to use a numeric value like a timestamp or a constant for the score. Hope this helps!
