### ISSUE TITLE
SETNX not working properly

### ISSUE THREAD

**Issue by tciuro** [mranney/node_redis#705]
Given the following snippet:

    var redis = require("redis"),
        client = redis.createClient();
        
    client.on("error", function (err) {
        console.log("error event - " + client.host + ":" + client.port + " - " + err);
    });

    client.del('sample:*', function (err, reply) {
    
        console.log('[del] err: ' + err);
        console.log('[del] reply: ' + reply);

    	client.setnx('sample:foo', 1, function (err, reply) {
            console.log('[setnx] err: ' + err);
        	console.log('[setnx] reply: ' + reply);
        	
        	client.quit(function (err, res) {
				console.log("Exiting from quit command.");
			});
        });
    });

I see the following output:

    [del] err: null
    [del] reply: 0
    [setnx] err: null
    [setnx] reply: 0
    Exiting from quit command.

Question: shouldn't `setnx` always work since its the key prefix is always deleted first? I was expecting a reply of '1', but I always get '0'. :-/

**Comment by mranney** [comment]
That's because redis doesn't support wildcards on the del command. Some solutions can be found here:

http://stackoverflow.com/questions/4006324/how-to-atomically-delete-keys-matching-a-pattern-using-redis

**Comment by tciuro** [comment]
Wow... what an omission! Looks like the potential solutions are ugly at best. Anyway, thanks for the help.

**Comment by dirkbonhomme** [comment]
I'm quite sure this is done for performance reasons since you can't predict the impact when using wildcards. That's why Redis warns against using the KEYS command as well.

**Comment by tciuro** [comment]
I see that some people are calling:

    EVAL "return redis.call('del', unpack(redis.call('keys', ARGV[1])))" 0 prefix:*

or from the command line:

    redis-cli KEYS "prefix:*" | xargs redis-cli DEL

There doesn't seem to be an obvious, clean way to remove keys via pattern. I understand that `KEYS()` may not be the best idea for a large set, but there should be a way to do it properly, regardless.

Also, at what point does performance start to degrade? At 1000? 10K? 1M keys? It's not clear anywhere in the documentation. I get the feeling that for most devs, calling KEYS() and DEL() while iterating will not be a performance issue.

**Comment by brycebaril** [comment]
It talks a little about it here: http://redis.io/commands/keys -- "For example, Redis running on an entry level laptop can scan a 1 million key database in 40 milliseconds."

Like with many things in NoSQL databases, the way to do this is to plan ahead -- if you know you will be deleting large families of things, store those families in a relationship that can be iterated.

If you're simply trying to do offline maintenance, the xargs version above or similar is common and easy, and keeps `KEYS *` from leading production developers down the wrong path.
