### ISSUE TITLE
Error: ERR wrong number of arguments for 'sadd' command

### ISSUE THREAD

**Issue by switz** [mranney/node_redis#709]
I can't get any `sadd` commands working on my server. They all work fine locally on my Macbook, but none work on my ubuntu server running node v0.11.14 and dokku-alt-redis.

This is run directly in the node REPL.

> redis.sadd("test2", 1, 2, 3, console.log)
true
> [Error: ERR wrong number of arguments for 'sadd' command]

> redis.sadd("test2", [1,2,3], console.log)
true
> [Error: ERR wrong number of arguments for 'sadd' command]

**Comment by brycebaril** [comment]
what version of Redis are you running?

**Comment by switz** [comment]
I'm using https://github.com/dokku-alt/dokku-alt/tree/master/plugins/dokku-redis - trying to figure out what version they use - I'll get back to you.

This only happens when trying to add multiple items, so I assume it's running a redis older than 2.4, but I do find that hard to believe.

**Comment by switz** [comment]
Looks like it's running off of stable: https://github.com/luxifer/dokku-redis-dockerfiles/blob/master/Dockerfile
