### ISSUE TITLE
High availability support in node_redis

### ISSUE THREAD

**Issue by saltukalakus** [mranney/node_redis#738]
I would like to use Redis in high available mode. Apparently node_redis does not support out of box.

There is one project (haredis)  https://github.com/carlos8f/haredis project . But looks like that project is dead with no commits since 2 years.

Another more promising is a small wrapper for Redis Sentinel. https://github.com/ortoo/node-redis-sentinel 

Is there a plan for build in support for HA in node_redis?

**Comment by saltukalakus** [comment]
As there are open issues on sentinel I would like to close the issue.

**Comment by BridgeAR** [comment]
Sentinel is going to build in at some point.
