### ISSUE TITLE
bgsave and other write-to-file operations

### ISSUE THREAD

**Issue by fickas** [mranney/node_redis#748]
Did I miss documentation on persistent operators? I am trying to use bgsave to dump my database to file. The operation executes but with no effect that I can see.

Also, Redis docs claim that having a file dump.rdb will automatically cause this to be installed on server start-up. Did not work for me with node.

**Comment by brycebaril** [comment]
Hi @fickas -- bgsave should work with node_redis just fine, and the dump.rdb file being loaded is entirely up to your redis configuration, outside of the scope of this library.

Your best bet is to check your Redis configuration
