### ISSUE TITLE
Multi doesn't abort on error?

### ISSUE THREAD

**Issue by Janpot** [mranney/node_redis#750]
If I understand correctly, when `multi` encounters an error the whole transaction should be aborted and rolled back. Yet when I execute following code:

```
var client = require('redis').createClient();
client.multi()
  .set('some-key', 1)
  .lset('some-key', 1, 1) // expected to error
  .set('some-key', 2)
  .get('some-key')
  .exec(function (err, result) {
    if (err) console.log('error', err);
    else console.log('success', result);
  });
```

I get the output:

```
success [ 'OK',
  'WRONGTYPE Operation against a key holding the wrong kind of value',
  'OK',
  '2' ]
```

No error is reported in the callback and all commands seem to have executed. Am I missing something?

**Comment by luin** [comment]
Redis does not support roll backs.

Reference:
http://redis.io/topics/transactions (Errors inside a transaction & Why Redis does not support roll backs?)

**Comment by Janpot** [comment]
@luin Ah, missed that. Makes sense. I misunderstood "Either all of the commands or none are processed". Thanks.
