### ISSUE TITLE
connect ECONNREFUSED

### ISSUE THREAD

**Issue by pisceswin** [mranney/node_redis#768]
> test.js

```js
var redis = require("redis"),
  client = redis.createClient();

client.on("error", function (err) {
  console.log("Error " + err);
});
```

+ redis-server
+ node test.js
+ redis-cli shutdown
``` sh
$ node test.js
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
```

### Why ‘on error’ is invalid?

**Comment by DiegoHuang** [comment]
I face the same question too. on v.2.6.3

**Comment by viztastic** [comment]
Same here...

![image](https://user-images.githubusercontent.com/8556736/30782501-b10df928-a176-11e7-810c-b88d7c6a9dea.png)

**Comment by kakasal** [comment]
same? all f** are sleeping
